In [1]:
import pandas as pd
from sqlalchemy import create_engine
pd.set_option('display.max_columns', None)

In [2]:
csv_file = "Business_Owners.csv"
owners_df = pd.read_csv(csv_file)
owners_df.head()

,Account Number,Legal Name,Owner First Name,Owner Middle Initial,Owner Last Name,Suffix,Legal Entity Owner,Title
0,57028,A LAVA & SONS CO,LEO,NaN,APPELBAUM,NaN,NaN,PRESIDENT
1,458385,"NANO CLASSICS, LLC",Amy,E,Runjavac-Duda,NaN,NaN,MANAGING MEMBER
2,362027,ENVIOS DE VALORES LA NACIONAL CORP.,Jon,C,Ness,NaN,NaN,CEO
3,456967,INOKO SUSHI RESTAURANT INC.,SHANSHAN,NaN,YU,NaN,NaN,SECRETARY
4,64406,"SEADOG VENTURES, INC.",LAUREN,NaN,BARAN,NaN,NaN,TREASURER

In [3]:
csv_file = "Business_Licenses_-_Current_Active.csv"
licenses_df = pd.read_csv(csv_file)
licenses_df.head()

/Users/anthonyproffit/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,BUSINESS ACTIVITY ID,BUSINESS ACTIVITY,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION
0,2753996-20201119,2753996,208984,1,THE FRANCES XAVIER WARDE SCHOOL NFP,THE FRANCES XAVIER WARDE SCHOOL NFP,751 N STATE ST,CHICAGO,IL,60610,42.0,56.0,42-56,18.0,1625,Raffles,720,Not-For-Profit Selling Raffles for Prizes of $...,2753996,ISSUE,10/09/2020,10/09/2020,10/09/2020,N,11/19/2020,05/15/2021,10/09/2020,11/19/2020,AAI,NaN,NaN,41.896422,-87.628046,"(41.89642201551983, -87.62804636360084)"
1,2704238-20200516,2723390,458482,2,"ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...","ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...",7173 W GRAND AVE GROUND,CHICAGO,IL,60707,29.0,38.0,29-38,25.0,1625,Raffles,720,Not-For-Profit Selling Raffles for Prizes of $...,2704238,RENEW,NaN,03/15/2020,11/24/2020,N,05/16/2020,05/15/2021,11/24/2020,11/25/2020,AAI,NaN,NaN,41.923768,-87.805433,"(41.9237675637846, -87.80543279195435)"
2,2712293-20201209,2712293,301145,3,ARMORED FLOORS INC.,Armored Floors Inc.,26212 W CHATHAM DR,PLAINFIELD,IL,60585,NaN,NaN,NaN,NaN,4404,Regulated Business License,755,Residential Installations,2712293,ISSUE,01/16/2020,01/16/2020,01/21/2020,N,12/09/2020,05/15/2021,01/21/2020,01/22/2020,AAI,NaN,NaN,NaN,NaN,NaN
3,2098002-20190516,2654568,206228,2,ENVIROPLUS INC,"ENVIROPLUS, INC",8044 LAWNDALE AVE 1 110,SKOKIE,IL,60076,NaN,NaN,NaN,NaN,1010,Limited Business License,NaN,NaN,2098002,RENEW,NaN,03/15/2019,07/30/2019,N,05/16/2019,05/15/2021,07/30/2019,07/31/2019,AAI,NaN,NaN,NaN,NaN,NaN
4,1479504-20190516,2653953,28087,2,HEZCORP CONSTRUCTION SER INC,"HEZCORP CONSTRUCTION SERV, INC",678 BROADWAY` ST 100,LIBERTYVILLE,IL,60048,NaN,NaN,NaN,NaN,1010,Limited Business License,NaN,NaN,1479504,RENEW,NaN,03/15/2019,05/01/2019,N,05/16/2019,05/15/2021,05/01/2019,05/01/2019,AAI,NaN,NaN,NaN,NaN,NaN

In [4]:
licenses_df = licenses_df.rename(columns={"ACCOUNT NUMBER": "Account Number"})
licenses_df.head()

,ID,LICENSE ID,Account Number,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,BUSINESS ACTIVITY ID,BUSINESS ACTIVITY,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION
0,2753996-20201119,2753996,208984,1,THE FRANCES XAVIER WARDE SCHOOL NFP,THE FRANCES XAVIER WARDE SCHOOL NFP,751 N STATE ST,CHICAGO,IL,60610,42.0,56.0,42-56,18.0,1625,Raffles,720,Not-For-Profit Selling Raffles for Prizes of $...,2753996,ISSUE,10/09/2020,10/09/2020,10/09/2020,N,11/19/2020,05/15/2021,10/09/2020,11/19/2020,AAI,NaN,NaN,41.896422,-87.628046,"(41.89642201551983, -87.62804636360084)"
1,2704238-20200516,2723390,458482,2,"ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...","ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...",7173 W GRAND AVE GROUND,CHICAGO,IL,60707,29.0,38.0,29-38,25.0,1625,Raffles,720,Not-For-Profit Selling Raffles for Prizes of $...,2704238,RENEW,NaN,03/15/2020,11/24/2020,N,05/16/2020,05/15/2021,11/24/2020,11/25/2020,AAI,NaN,NaN,41.923768,-87.805433,"(41.9237675637846, -87.80543279195435)"
2,2712293-20201209,2712293,301145,3,ARMORED FLOORS INC.,Armored Floors Inc.,26212 W CHATHAM DR,PLAINFIELD,IL,60585,NaN,NaN,NaN,NaN,4404,Regulated Business License,755,Residential Installations,2712293,ISSUE,01/16/2020,01/16/2020,01/21/2020,N,12/09/2020,05/15/2021,01/21/2020,01/22/2020,AAI,NaN,NaN,NaN,NaN,NaN
3,2098002-20190516,2654568,206228,2,ENVIROPLUS INC,"ENVIROPLUS, INC",8044 LAWNDALE AVE 1 110,SKOKIE,IL,60076,NaN,NaN,NaN,NaN,1010,Limited Business License,NaN,NaN,2098002,RENEW,NaN,03/15/2019,07/30/2019,N,05/16/2019,05/15/2021,07/30/2019,07/31/2019,AAI,NaN,NaN,NaN,NaN,NaN
4,1479504-20190516,2653953,28087,2,HEZCORP CONSTRUCTION SER INC,"HEZCORP CONSTRUCTION SERV, INC",678 BROADWAY` ST 100,LIBERTYVILLE,IL,60048,NaN,NaN,NaN,NaN,1010,Limited Business License,NaN,NaN,1479504,RENEW,NaN,03/15/2019,05/01/2019,N,05/16/2019,05/15/2021,05/01/2019,05/01/2019,AAI,NaN,NaN,NaN,NaN,NaN

In [5]:

overall = pd.merge(licenses_df, owners_df, how="left", on="Account Number")
overall.head()

,ID,LICENSE ID,Account Number,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,WARD,PRECINCT,WARD PRECINCT,POLICE DISTRICT,LICENSE CODE,LICENSE DESCRIPTION,BUSINESS ACTIVITY ID,BUSINESS ACTIVITY,LICENSE NUMBER,APPLICATION TYPE,APPLICATION CREATED DATE,APPLICATION REQUIREMENTS COMPLETE,PAYMENT DATE,CONDITIONAL APPROVAL,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,Legal Name,Owner First Name,Owner Middle Initial,Owner Last Name,Suffix,Legal Entity Owner,Title
0,2753996-20201119,2753996,208984,1,THE FRANCES XAVIER WARDE SCHOOL NFP,THE FRANCES XAVIER WARDE SCHOOL NFP,751 N STATE ST,CHICAGO,IL,60610,42.0,56.0,42-56,18.0,1625,Raffles,720,Not-For-Profit Selling Raffles for Prizes of $...,2753996,ISSUE,10/09/2020,10/09/2020,10/09/2020,N,11/19/2020,05/15/2021,10/09/2020,11/19/2020,AAI,NaN,NaN,41.896422,-87.628046,"(41.89642201551983, -87.62804636360084)",THE FRANCES XAVIER WARDE SCHOOL NFP,ALBERT,A,BOUMENOT,NaN,NaN,PRINCIPAL OFFICER
1,2753996-20201119,2753996,208984,1,THE FRANCES XAVIER WARDE SCHOOL NFP,THE FRANCES XAVIER WARDE SCHOOL NFP,751 N STATE ST,CHICAGO,IL,60610,42.0,56.0,42-56,18.0,1625,Raffles,720,Not-For-Profit Selling Raffles for Prizes of $...,2753996,ISSUE,10/09/2020,10/09/2020,10/09/2020,N,11/19/2020,05/15/2021,10/09/2020,11/19/2020,AAI,NaN,NaN,41.896422,-87.628046,"(41.89642201551983, -87.62804636360084)",THE FRANCES XAVIER WARDE SCHOOL NFP,KELLY,NaN,CHERF,NaN,NaN,SECRETARY
2,2753996-20201119,2753996,208984,1,THE FRANCES XAVIER WARDE SCHOOL NFP,THE FRANCES XAVIER WARDE SCHOOL NFP,751 N STATE ST,CHICAGO,IL,60610,42.0,56.0,42-56,18.0,1625,Raffles,720,Not-For-Profit Selling Raffles for Prizes of $...,2753996,ISSUE,10/09/2020,10/09/2020,10/09/2020,N,11/19/2020,05/15/2021,10/09/2020,11/19/2020,AAI,NaN,NaN,41.896422,-87.628046,"(41.89642201551983, -87.62804636360084)",THE FRANCES XAVIER WARDE SCHOOL NFP,MARY,NaN,REILING,NaN,NaN,PRESIDENT
3,2704238-20200516,2723390,458482,2,"ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...","ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...",7173 W GRAND AVE GROUND,CHICAGO,IL,60707,29.0,38.0,29-38,25.0,1625,Raffles,720,Not-For-Profit Selling Raffles for Prizes of $...,2704238,RENEW,NaN,03/15/2020,11/24/2020,N,05/16/2020,05/15/2021,11/24/2020,11/25/2020,AAI,NaN,NaN,41.923768,-87.805433,"(41.9237675637846, -87.80543279195435)","ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...",ROBERT,J,ARENS,NaN,NaN,PRESIDENT
4,2704238-20200516,2723390,458482,2,"ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...","ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...",7173 W GRAND AVE GROUND,CHICAGO,IL,60707,29.0,38.0,29-38,25.0,1625,Raffles,720,Not-For-Profit Selling Raffles for Prizes of $...,2704238,RENEW,NaN,03/15/2020,11/24/2020,N,05/16/2020,05/15/2021,11/24/2020,11/25/2020,AAI,NaN,NaN,41.923768,-87.805433,"(41.9237675637846, -87.80543279195435)","ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...",PAUL,NaN,BEZAZIAN,NaN,NaN,SECRETARY

In [6]:
list(overall.columns)

['ID',
 'LICENSE ID',
 'Account Number',
 'SITE NUMBER',
 'LEGAL NAME',
 'DOING BUSINESS AS NAME',
 'ADDRESS',
 'CITY',
 'STATE',
 'ZIP CODE',
 'WARD',
 'PRECINCT',
 'WARD PRECINCT',
 'POLICE DISTRICT',
 'LICENSE CODE',
 'LICENSE DESCRIPTION',
 'BUSINESS ACTIVITY ID',
 'BUSINESS ACTIVITY',
 'LICENSE NUMBER',
 'APPLICATION TYPE',
 'APPLICATION CREATED DATE',
 'APPLICATION REQUIREMENTS COMPLETE',
 'PAYMENT DATE',
 'CONDITIONAL APPROVAL',
 'LICENSE TERM START DATE',
 'LICENSE TERM EXPIRATION DATE',
 'LICENSE APPROVED FOR ISSUANCE',
 'DATE ISSUED',
 'LICENSE STATUS',
 'LICENSE STATUS CHANGE DATE',
 'SSA',
 'LATITUDE',
 'LONGITUDE',
 'LOCATION',
 'Legal Name',
 'Owner First Name',
 'Owner Middle Initial',
 'Owner Last Name',
 'Suffix',
 'Legal Entity Owner',
 'Title']

In [7]:
overall.columns = overall.columns.str.upper()

In [8]:
overall = overall.drop(columns=['LEGAL NAME',
                      'SITE NUMBER',
                      'WARD',
                      'WARD PRECINCT',
                      'POLICE DISTRICT',
                      'LICENSE CODE',
                      'BUSINESS ACTIVITY ID',
                      'LICENSE STATUS CHANGE DATE',
                      'SSA',
                      'LATITUDE',
                      'LONGITUDE',
                      'LOCATION',
                      'LEGAL NAME',
                      'OWNER MIDDLE INITIAL',
                      'SUFFIX',
                      'LEGAL ENTITY OWNER'])

In [9]:
list(overall.columns)

['ID',
 'LICENSE ID',
 'ACCOUNT NUMBER',
 'DOING BUSINESS AS NAME',
 'ADDRESS',
 'CITY',
 'STATE',
 'ZIP CODE',
 'PRECINCT',
 'LICENSE DESCRIPTION',
 'BUSINESS ACTIVITY',
 'LICENSE NUMBER',
 'APPLICATION TYPE',
 'APPLICATION CREATED DATE',
 'APPLICATION REQUIREMENTS COMPLETE',
 'PAYMENT DATE',
 'CONDITIONAL APPROVAL',
 'LICENSE TERM START DATE',
 'LICENSE TERM EXPIRATION DATE',
 'LICENSE APPROVED FOR ISSUANCE',
 'DATE ISSUED',
 'LICENSE STATUS',
 'OWNER FIRST NAME',
 'OWNER LAST NAME',
 'TITLE']

In [10]:
overall = overall.rename(columns={'ID': "ID",
                                  'LICENSE ID': 'LICENSE_ID',
                                     'ACCOUNT NUMBER': 'ACCOUNT_NUMBER',
                                     'DOING BUSINESS AS NAME': 'DOING_BUSINESS_AS_NAME',
                                     'ZIP CODE':'ZIP_CODE',
                                     'LICENSE DESCRIPTION':'LICENSE_DESCRIPTION',
                                     'BUSINESS ACTIVITY':'BUSINESS_ACTIVITY',
                                     'LICENSE NUMBER':'LICENSE_NUMBER',
                                     'APPLICATION TYPE':'APPLICATION_TYPE',
                                     'APPLICATION CREATED DATE':'APPLICATION_CREATED_DATE',
                                     'APPLICATION REQUIREMENTS COMPLETE':'APPLICATION_REQUIREMENTS_COMPLETE',
                                     'PAYMENT DATE':'PAYMENT_DATE',
                                     'CONDITIONAL APPROVAL':'CONDITIONAL_APPROVAL',
                                     'LICENSE TERM START DATE':'LICENSE_TERM_START_DATE',
                                     'LICENSE TERM EXPIRATION DATE':'LICENSE_TERM_EXPIRATION_DATE',
                                     'LICENSE APPROVED FOR ISSUANCE':'LICENSE_APPROVED_FOR_ISSUANCE',
                                     'DATE ISSUED':'DATE_ISSUED',
                                     'LICENSE STATUS':'LICENSE_STATUS',
                                     'OWNER FIRST NAME':'OWNER_FIRST_NAME',
                                     'OWNER LAST NAME':'OWNER_LAST_NAME'})

In [11]:
overall.columns = overall.columns.str.lower()
overall.head()

,id,license_id,account_number,doing_business_as_name,address,city,state,zip_code,precinct,license_description,business_activity,license_number,application_type,application_created_date,application_requirements_complete,payment_date,conditional_approval,license_term_start_date,license_term_expiration_date,license_approved_for_issuance,date_issued,license_status,owner_first_name,owner_last_name,title
0,2753996-20201119,2753996,208984,THE FRANCES XAVIER WARDE SCHOOL NFP,751 N STATE ST,CHICAGO,IL,60610,56.0,Raffles,Not-For-Profit Selling Raffles for Prizes of $...,2753996,ISSUE,10/09/2020,10/09/2020,10/09/2020,N,11/19/2020,05/15/2021,10/09/2020,11/19/2020,AAI,ALBERT,BOUMENOT,PRINCIPAL OFFICER
1,2753996-20201119,2753996,208984,THE FRANCES XAVIER WARDE SCHOOL NFP,751 N STATE ST,CHICAGO,IL,60610,56.0,Raffles,Not-For-Profit Selling Raffles for Prizes of $...,2753996,ISSUE,10/09/2020,10/09/2020,10/09/2020,N,11/19/2020,05/15/2021,10/09/2020,11/19/2020,AAI,KELLY,CHERF,SECRETARY
2,2753996-20201119,2753996,208984,THE FRANCES XAVIER WARDE SCHOOL NFP,751 N STATE ST,CHICAGO,IL,60610,56.0,Raffles,Not-For-Profit Selling Raffles for Prizes of $...,2753996,ISSUE,10/09/2020,10/09/2020,10/09/2020,N,11/19/2020,05/15/2021,10/09/2020,11/19/2020,AAI,MARY,REILING,PRESIDENT
3,2704238-20200516,2723390,458482,"ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...",7173 W GRAND AVE GROUND,CHICAGO,IL,60707,38.0,Raffles,Not-For-Profit Selling Raffles for Prizes of $...,2704238,RENEW,NaN,03/15/2020,11/24/2020,N,05/16/2020,05/15/2021,11/24/2020,11/25/2020,AAI,ROBERT,ARENS,PRESIDENT
4,2704238-20200516,2723390,458482,"ARMED FORCES POST 8322, VETERANS OF FOREIGN WA...",7173 W GRAND AVE GROUND,CHICAGO,IL,60707,38.0,Raffles,Not-For-Profit Selling Raffles for Prizes of $...,2704238,RENEW,NaN,03/15/2020,11/24/2020,N,05/16/2020,05/15/2021,11/24/2020,11/25/2020,AAI,PAUL,BEZAZIAN,SECRETARY

In [12]:
overall.dtypes

id                                    object
license_id                             int64
account_number                         int64
doing_business_as_name                object
address                               object
city                                  object
state                                 object
zip_code                              object
precinct                             float64
license_description                   object
business_activity                     object
license_number                         int64
application_type                      object
application_created_date              object
application_requirements_complete     object
payment_date                          object
conditional_approval                  object
license_term_start_date               object
license_term_expiration_date          object
license_approved_for_issuance         object
date_issued                           object
license_status                        object
owner_first_name                      object
owner_last_name                       object
title                                 object
dtype: object

In [13]:
overall.set_index("id", inplace=True)

In [14]:
rds_connection_string = "postgres:Falcons01!@localhost:5432/business_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [15]:
engine.table_names()

['overall']

In [16]:
overall.to_sql(name='overall', con=engine, if_exists='append', index=True)